volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8.3-fpm-alpine
        working_dir: /var/www
        depends_on:
            - mysql
        command: >
            sh -c "docker-php-ext-install pdo pdo_mysql && php -S 0.0.0.0:8080 -t public"
        environment:
            docker: "true"
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - slim-network
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - slim-network
networks:
    slim-network:
        driver: bridge