volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8.3-alpine
        working_dir: /var/www
        depends_on:
            - mysql
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - slim-network
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - slim-network
networks:
    slim-network:
        driver: bridge